[package]
name = "memo"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "memo"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
base64.workspace = true
clap.workspace = true
memo-client = { path = "../memo-client" }
memo-core = { path = "../memo-core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
time.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
